django/student_crud/student_crud/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
    path('student/',include('student_app.urls')),
    path('teacher/',include('teacher_crud.urls')),
    path('library/',include('library_crud.urls')),
    path('registration/',include('student_registration.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django/student_crud/student_registration/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.registration_list, name='list'),
    path('create/', views.registration_form, name='form'),
    path('<int:pk>/', views.view_registration, name='view'),
    path('<int:pk>/edit/',views.update_registration, name='update'),
    path('<int:pk>/delete/', views.delete_registration, name='delete'),
]

django/student_crud/students/urls.py
from django.urls import path
from . import views

urlpatterns = [
  
    path('', views.index, name='index'),
    path('about', views.about_us, name='about-us'),
    path('services', views.services, name='services'),
    path('contact', views.contactus, name='contact'),
]

django/student_crud/student_registration/models.py
from django.db import models

# Create your models here.
class Registration(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Others'),

    ]
    BRANCH_CHOICES = [
        ('CS', 'Comuter Science'),
        ('EC', 'Electronics & Communications'),
        ('ME', 'Mechanical'),
        ('CV', 'Civil'),
    ]

    name = models.CharField(max_length=100)
    age = models.IntegerField()
    usn = models.CharField(max_length=100, unique=True)
    branch = models.CharField(max_length=50, choices= BRANCH_CHOICES)
    sem = models.IntegerField()
    course = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices= GENDER_CHOICES)
    email = models.EmailField()
    hobbies = models.JSONField(default=list)
    address = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(upload_to='images/', blank=True, null=True)
    resume_pdf = models.FileField(upload_to='pdfs/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

django/student_crud/student_registration/forms.py
from django import forms
from .models import Registration

class RegistrationForm(forms.ModelForm):
    hobbies = forms.MultipleChoiceField(
        choices = [
            ('sports', "Sports"),
            ('music', "Music"),
            ('singing', "Singing"),
            ('dancing', "Dancing"),
            ('reading', "Reading"),
            ('traveling', "Traveling"),
        ],
        widget=forms.CheckboxSelectMultiple(),

    )
    address = forms.CharField(
         widget=forms.Textarea(attrs={
            'rows': 3,
            'placeholder': 'Enter the address',
            'class': 'form-control',
         })

    )

    class Meta:
        model = Registration
        fields = '__all__'
     
        widgets = {
            'name': forms.TextInput(attrs= {'class': 'form-control', 'placeholder': "Enter your full name"}),
            'age': forms.NumberInput(attrs= {'class': 'form-control', 'placeholder': "Enter your full age"}),
            'usn': forms.TextInput(attrs= {'class': 'form-control', 'placeholder': "Enter your usn"}),
            'email': forms.TextInput(attrs= {'class': 'form-control', 'placeholder': "Enter your email-id"}),
            'branch': forms.Select(attrs= {'class': 'form-select'}),
            'sem': forms.NumberInput(attrs= {'class': 'form-control', 'placeholder': "Enter your full semester"}),
            'course': forms.TextInput(attrs= {'class': 'form-control', 'placeholder': "Enter your full course"}),
            'gender': forms.RadioSelect(attrs= {'class': 'form-check'}),
            'profile_image': forms.ClearableFileInput(attrs= {'class': 'form-control'}),
            'resume_pdf': forms.ClearableFileInput(attrs= {'class': 'form-control'}),                   
        }
      

django/student_crud/student_registration/views.py
from django.shortcuts import render, redirect , get_object_or_404
from .forms import RegistrationForm
from .models import Registration

# Create your views here.
def registration_list(request):
    students = Registration.objects.all()
    return render(request, "student_registration/registration_list.html", {'students': students})

def registration_form(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('list')
    else:
        form = RegistrationForm()        
    return render(request, "student_registration/registration_form.html", {'form': form})

def view_registration(request, pk):
    student = get_object_or_404(Registration, pk=pk)
    return render(request, "student_registration/view_registration.html",{'student': student})

def update_registration(request, pk):
    student = get_object_or_404(Registration, pk=pk)
    if request.method == 'POST':
        form = RegistrationForm(request.POST,request.FILES, instance=student)
        if form.is_valid():
            form.save()
            return redirect('list')
    else:
        form = RegistrationForm(instance=student)
    return render(request, "student_registration/registration_form.html", {'form': form})
    
def delete_registration(request, pk):
    student = get_object_or_404(Registration, pk=pk)
    if request.method == 'POST':
        student.delete()
        return redirect('list')
    return render(request, "student_registration/delete_registration.html", {'student': student})

django/student_crud/student_registration/templates/student_registration/delete_registration.html
{% extends 'student_registration/menu.html' %}

{% block title %}Student Registration List{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h1>Delete the Existing Student Registration</h1>
        </div>
        <div class="card-body">
            <h2>Do you really want to delete the  registration details of {{student.name}}</h2>
            </div>
        <div class="card-footer">
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class=" btn btn-success">Yes</button>
                    <a class="btn btn-danger" href="{% url 'list' %}">No</a>
                </form>
                </div>
        </div>

{% endblock %}

django/student_crud/student_registration/templates/student_registration/menu.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block styles %}{% endblock %}
  </head>
  <body>
  
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Student Registration</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'list' %}">Registration List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'form' %}">Make a new Registration</a>
              </li>
            
            </ul>
          </div>
        </div>
      </nav>
      <div class="container"></div>
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

django/student_crud/student_registration/templates/student_registration/registration_form.html
{% extends 'student_registration/menu.html' %}

{% block title %}Student Registration List{% endblock title %}

{% block styles %}
<style>
      #id_gender div:first-child{
            display: none
      }

      #id_gender label {
            display: flex;
            gap: 10px;
      }
</style>
{% endblock %}

{% block content %}
      <h1>{% if form.instance.pk %}Edit Student Registration{% else %} Student Registration Form {% endif %}</h1>
      <form method="post" enctype="multipart/form-data" class="mt-3">
            {% csrf_token %}
            <div class="mb-3">
                  {{ form.as_p}}
            </div>
            <button type="submit" class="btn {% if form.instance.pk %}btn-warning{% else %} btn-success {% endif %}">Submit</button>
           <a href="{% url 'list' %}" class="btn btn-danger">Cancel</a>
      </form>
{% endblock %}

django/student_crud/student_registration/templates/student_registration/registration_list.html
{% extends 'student_registration/menu.html' %}

{% block title %}Student Registration List{% endblock title %}

{% block content %}
    <h1>List of Student Registration</h1>
    <table class="table table-warning table-bordered border-1 table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">USN</th>
            <th scope="col">Branch</th>
            <th scope="col">Sem</th>
            <th scope="col">Course</th>
            <th scope="col">Gender</th>
            <th scope="col">Email ID</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for student in students %}
          <tr>
          <td>{{student.name}}</td>
            <td>{{student.age}}</td>
            <td>{{student.usn}}</td>
            <td>{{student.branch}}</td>
            <td>{{student.sem}}</td>
            <td>{{student.course}}</td>
            <td>{{student.gender}}</td>
            <td>{{student.email_id}}</td>
            <td>
              <a href="{% url 'view' student.pk %}" class="btn btn-secondary btn-sm">View</a>
              <a href="{% url 'update' student.pk %}" class="btn btn-warning btn-sm">Edit</a>
              <a href="{% url 'delete' student.pk %}" class="btn btn-danger btn-sm">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
 {% endblock %}

django/student_crud/student_registration/templates/student_registration/view_registration.html
{% extends 'student_registration/menu.html' %}

{% block title %}view Registration{% endblock title %}

{% block content %}
     <h1 class="bg-secondary text-light text-center">Registration Details of {{student.name}}</h1>
     <table class="table table-warning">
          <tr>
               <th>Name:</th>
               <td>{{student.name}}</td>
          </tr>
          <tr>
               <th>Age:</th>
               <td>{{student.age}}</td>
          </tr>
          
          <tr>
               <th>USN:</th>
               <td>{{student.usn}}</td>  
          </tr>
          <tr>
               <th>Branch:</th>
               <td>{{student.branch}}</td>  
          </tr>
          <tr>
               <th>Semester:</th>
               <td>{{student.sem}}</td>  
          </tr>
          <tr>
               <th>Gender:</th>
               <td>{{student.gender}}</td>  
          </tr>
          <tr>
               <th>Email ID:</th>
               <td>{{student.email_id}}</td>  
          </tr>
          <tr>
               <th>Hobbies:</th>
               <td>{{student.hobbies|join:", "}}</td>  
          </tr>
          <tr>
               <th>Address:</th>
               <td>{{student.address}}</td>  
          </tr>
          {% if student.profile_image %}
          <tr>
               <th>Profile Image:</th>
               <td><img src="{{student.profile_image.url}}" class="img-thumbnail" width="200"></td>  
          </tr>
          {% endif %}
          {% if student.resume_pdf %}
          <tr>
               <th>Resume:</th>
               <td><iframe src="{{student.resume_pdf.url}}"></iframe></td>
               <!-- <td><a href="{{student.resume_pdf.url}}" target="_blank">Download PDF</a></td>   -->
          </tr>
          {% endif %}
     </table>
{% endblock %}